# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Remote Deploy Using Docker Compose

on:
  push:
    branches: ["main"]
env:
  REMOTE_HOST: 1044665-cp29323.tw1.ru
  DOCKER_IMAGE_NAME: lembutt/itmo-docker-task-7:latest
jobs:
  test_build:
    name: Testing New Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.test.yml"
      - run: npm i
      - run: npm run test
  push_to_registry:
    needs: test_build
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: my-docker-hub-namespace/my-docker-hub-repository
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}
          labels: ${{ steps.meta.outputs.labels }}
  pull_latest_image:
    needs: push_to_registry
    name: Pulling Latest Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Pull Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: docker pull ${{ env.DOCKER_IMAGE_NAME }}
  deploy:
    needs: pull_latest_image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: ${{ env.REMOTE_HOST }}
        ssh_private_key: ${{ secrets.SSH_KEY }}
        ssh_user: ${{ secrets.SSH_USER }}
        docker_compose_prefix: 1044665_cp29323
        docker_compose_filename: docker-compose.yml